//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomNayAnGi.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialUnitMapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaterialUnitMapping()
        {
            this.Ingredients = new HashSet<Ingredient>();
        }
    
        public int id { get; set; }
        public int unitId { get; set; }
        public int materialId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingredient> Ingredients { get; set; }
        public virtual Material Material { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
