//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomNayAnGi.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int id { get; set; }
        public int userId { get; set; }
        public Nullable<int> recipeId { get; set; }
        public decimal amount { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string type { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
